### ISSUE TITLE
Unable to load songs with oculus quest

### ISSUE THREAD

**Issue by Shabbypenguin** [tommaier123/NoodleManager#3]
Loading up the program it doesnt appear to be responsive until dir is selected and it finds a valid synthriders installation. I am unable to do that, with the oculus quest version.

**Comment by Shabbypenguin** [comment]
https://github.com/tommaier123/NoodleManager/blob/master/NoodleManager/SettingsMenu.cs#L42

after looking at the code i understand now what the issue is. Making a folder named "CustomSongs" inside the release folder and setting the path to the release folder allows me to now send custom songs to my oculus.

perhaps making the dir specifically for custom songs and not the dir + extra folder would be less confusing for newcomers.

**Comment by tommaier123** [comment]
I agree this is just a quick and dirty solution. I wanted people who have the game on the PC to be able to just push their whole songs folder. In the future I am just going to add a folder browser dialog where you can select which folder to push.
