### ISSUE TITLE
Song preview does not play anything and is automatically stopped after 1s

### ISSUE THREAD

**Issue by Seika85** [tommaier123/NoodleManager#7]
I'm using Noodle Manager 1.4.1. A couple of weeks ago it worked as intended.
Today I wanted to preview songs before downloading them, like I used to do.

If I click the play button it turns red (as if playing) but there is no playback at all and after maybe 1s the button turns white again, ready to start the preview.

I tried this with several songs, even songs I have previewed previously.

I also tried deleting Noodle Manager and re-downloading/re-extracting it to no avail.

I did not actively install any other software since the last time I used Noodle Manager successfully. The only things (passively) installed were Windows Updates.

**Comment by tommaier123** [comment]
This feature is currently not supported throught the API anymore. In my rewrite of the NoodleManager previews will be done differently.
